name: zarity_twilio
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  twilio_programmable_video: ^1.0.2
  # Send http request
  http: ^0.13.5
  dio: ^5.1.1

  # Bloc
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  permission_handler: ^10.2.0
  
  # Functional programming
  dartz: ^0.10.1

  uuid: ^3.0.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

flutter:
  uses-material-design: true
